/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChuckMoviesIndexRouteImport } from './routes/chuck-movies/index'
import { Route as ChuckMoviesIdRouteImport } from './routes/chuck-movies/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuckMoviesIndexRoute = ChuckMoviesIndexRouteImport.update({
  id: '/chuck-movies/',
  path: '/chuck-movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuckMoviesIdRoute = ChuckMoviesIdRouteImport.update({
  id: '/chuck-movies/$id',
  path: '/chuck-movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chuck-movies/$id': typeof ChuckMoviesIdRoute
  '/chuck-movies': typeof ChuckMoviesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chuck-movies/$id': typeof ChuckMoviesIdRoute
  '/chuck-movies': typeof ChuckMoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chuck-movies/$id': typeof ChuckMoviesIdRoute
  '/chuck-movies/': typeof ChuckMoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chuck-movies/$id' | '/chuck-movies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chuck-movies/$id' | '/chuck-movies'
  id: '__root__' | '/' | '/chuck-movies/$id' | '/chuck-movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChuckMoviesIdRoute: typeof ChuckMoviesIdRoute
  ChuckMoviesIndexRoute: typeof ChuckMoviesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuck-movies/': {
      id: '/chuck-movies/'
      path: '/chuck-movies'
      fullPath: '/chuck-movies'
      preLoaderRoute: typeof ChuckMoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuck-movies/$id': {
      id: '/chuck-movies/$id'
      path: '/chuck-movies/$id'
      fullPath: '/chuck-movies/$id'
      preLoaderRoute: typeof ChuckMoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChuckMoviesIdRoute: ChuckMoviesIdRoute,
  ChuckMoviesIndexRoute: ChuckMoviesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
